stages:
    - test
    - deploy

sast:
    stage: test
    image: docker:stable
    variables:
      DOCKER_DRIVER: overlay2
    allow_failure: true
    services:
      - docker:stable-dind
    script:
      - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
      - docker run
          --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
          --volume "$PWD:/code"
          --volume /var/run/docker.sock:/var/run/docker.sock
          "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
    artifacts:
      paths: [gl-sast-report.json]

unit-3:
    stage: test
    script:
        - apt-get update -qq && apt-get install -y -qq python3 python3-pip
        - pip3 install django sakaiauthenticator
        - python3 --version
        - python3 -m django --version
        - python3 ./manage.py test --parallel 5

staging:
    stage: deploy
    script:
        - apt-get update && apt-get install -y -qq ansible git
        - ./scripts/deploy.sh
    environment:
        name: staging
        url: https://bubbles.paddatrapper.com
    only:
        - master
