include:
  - template: SAST.gitlab-ci.yml

stages:
  - test
  - deploy

variables:
  SAST_EXCLUDED_PATHS: "bubbles/static/vendor, spec, test, tests, tmp"

unit-3:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq python3 python3-pip
    - pip3 install -r requirements.txt
    - python3 --version
    - python3 -m django --version
    - python3 ./manage.py test --parallel 5

docker-image:
  stage: deploy
  image: docker:19
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:19-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:dev
  only:
    - master

docker-nginx-image:
  stage: deploy
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
    - cd nginx
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_NGINX_IMAGE:dev || true
    - docker build --cache-from $CI_REGISTRY_NGINX_IMAGE:dev --tag $CI_REGISTRY_NGINX_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_NGINX_IMAGE:dev .
    - docker push $CI_REGISTRY_NGINX_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_NGINX_IMAGE:dev
  only:
    - master
