include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  DS_DISABLE_REMOTE_CHECKS: "true"

stages:
  - test
  - deploy

unit-3:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq python3 python3-pip
    - pip3 install -r requirements.txt
    - python3 --version
    - python3 -m django --version
    - python3 ./manage.py test --parallel 5

staging:
  stage: deploy
  script:
    - apt-get update && apt-get install -y -qq ansible git
    - ./scripts/deploy.sh
  environment:
    name: staging
    url: https://bubbles.paddatrapper.com
  only:
    - master

docker-image:
  stage: deploy
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:dev || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:dev --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:dev
  only:
    - master
