stages:
    - test
    - deploy

test:unit-3:
    script:
        - apt-get update -qq && apt-get install -y -qq python3 python3-django python3-pip
        - python3 --version
        - python3 -m django --version
        - pip3 install sakaiauthenticator
        - python3 ./manage.py test --parallel 5

deploy:staging:
    stage: deploy
    script:
        - apt-get update && apt-get install -y -qq ansible git
        - ./scripts/deploy.sh
    environment:
        name: staging
        url: https://bubbles.paddatrapper.com
    only:
        - master
