version: "3"

services:
  db:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: bubbles
      POSTGRES_USER: bubbles
      POSTGRES_PASSWORD: bubbles_dev
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    restart: always
    build: ./
    command: [./docker/docker-entrypoint.dev.sh]
    volumes:
      - ./:/app:rw
    depends_on:
      - db
    env_file:
      - docker/dev.env
    ports:
      - "8000:8000"

volumes:
  postgres:
