version: "3"

services:
  bubbles:
    restart: always
    build: ./
    command: [/app/docker/docker-entrypoint.prod.sh]
    env_file:
      - docker/prod.env
    volumes:
      - static_volume:/app/staticfiles
      - /srv/media:/app/bubbles/media:rw
    expose:
      - 8000
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - /srv/media:/srv/media:rw
    ports:
      - 5000:5000
    depends_on:
      - bubbles

volumes:
  static_volume:
