# Generated by Django 2.0.6 on 2018-07-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bcd",
            options={"verbose_name": "BCD"},
        ),
        migrations.AlterModelOptions(
            name="booties",
            options={"verbose_name_plural": "Booties"},
        ),
        migrations.AlterModelOptions(
            name="fins",
            options={"verbose_name_plural": "Fins"},
        ),
        migrations.AlterField(
            model_name="item",
            name="state",
            field=models.CharField(
                choices=[
                    ("A", "Available"),
                    ("U", "In use"),
                    ("B", "Broken"),
                    ("R", "Repair"),
                    ("C", "Condemned"),
                ],
                default=("A", "Available"),
                max_length=1,
                verbose_name="State",
            ),
        ),
    ]
