# Generated by Django 2.0.6 on 2018-11-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_item_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, unique=True, verbose_name="Type"),
                ),
                ("cost", models.IntegerField(default=0, verbose_name="Value")),
            ],
        ),
        migrations.AlterField(
            model_name="fins",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "Extra small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra large"),
                ],
                max_length=2,
                verbose_name="Size",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="state",
            field=models.CharField(
                choices=[
                    ("A", "Available"),
                    ("U", "In use"),
                    ("B", "Broken"),
                    ("R", "Repair"),
                    ("C", "Condemned"),
                    ("M", "Missing"),
                ],
                default=("A", "Available"),
                max_length=1,
                verbose_name="State",
            ),
        ),
    ]
