# Generated by Django 2.1.5 on 2019-08-12 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_item_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cylinder",
            name="hydro_period",
            field=models.DurationField(
                default=datetime.timedelta(days=1456),
                verbose_name="Hydro-static test validity period",
            ),
        ),
    ]
