# Generated by Django 2.2.4 on 2019-09-05 15:35
import datetime

from django.db import migrations


def fix_cylinder_hydro(apps, schema_editor):
    Cylinder = apps.get_model("inventory", "Cylinder")
    for cylinder in Cylinder.objects.filter(capacity__lt=40.0):
        cylinder.hydro_period = datetime.timedelta(weeks=208)
        cylinder.save()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_auto_20190812_2000"),
    ]

    operations = [
        migrations.RunPython(fix_cylinder_hydro),
    ]
