# Generated by Django 2.2.28 on 2022-09-20 06:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_auto_20191119_1649"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="bcd",
            managers=[
                ("item_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="booties",
            managers=[
                ("item_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="cylinder",
            managers=[
                ("item_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="fins",
            managers=[
                ("item_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="item",
            managers=[
                ("item_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="regulator",
            managers=[
                ("item_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="wetsuit",
            managers=[
                ("item_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
