# Generated by Django 2.0.6 on 2018-07-05 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalperiod',
            name='period',
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End date'),
            preserve_default=False,
        ),
    ]
