# Generated by Django 2.0.6 on 2018-08-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0005_requestitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestitem",
            name="cost",
            field=models.IntegerField(default=0, verbose_name="Cost"),
        ),
    ]
