# Generated by Django 2.1.5 on 2019-01-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_weightrequestitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightrequestitem',
            name='rental',
        ),
        migrations.AddField(
            model_name='rental',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.DeleteModel(
            name='WeightRequestItem',
        ),
    ]
