# Generated by Django 2.0.6 on 2018-11-21 15:51

from django.db import migrations

def fix_return_item_state(apps, schema_editor):
    RentalItem = apps.get_model('rentals', 'RentalItem')
    Item = apps.get_model('inventory', 'Item')
    for item in Item.objects.filter(state='U'):
        current_rentals = RentalItem.objects.filter(item=item, returned=False)
        if current_rentals.count() == 0:
            item.state = 'A'
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_auto_20190107_1521'),
    ]

    operations = [
        migrations.RunPython(fix_return_item_state),
    ]
