# Generated by Django 2.2.4 on 2019-10-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_rentalperiod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='item_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
    ]
