# Generated by Django 2.2.4 on 2019-10-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0013_requestitem_item_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestitem",
            name="item_size",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Size"
            ),
        ),
    ]
