# Generated by Django 2.2.10 on 2020-02-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0015_auto_20191119_1642"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rental",
            options={"permissions": [("free_rental", "Can rent gear without paying")]},
        ),
    ]
